### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by BHess2653**

### CODE REVIEW

**Review by LukeBillington — CHANGES_REQUESTED** [review]
Hey Brandon, this looks good, I suggest updating your readme with contributing and style guide instructions, or create a contributing file.

**Comment by BHess2653** [comment]
I made changes to my README about mocha and testing

**Review by LukeBillington — APPROVED** [review]

**Comment by LukeBillington** [comment]
LGTM :D Nice work!

**Comment by nambihawkins** [comment]
Brandon, I would like to recommend adding comments to your main.js file.

**Pull request merged**
